apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-app-ingress
  namespace: production
spec:
  ingressClassName: nginx
  rules:
  - host: 
    http:
      paths:
        - path: /wordpress
          pathType: Prefix          
          backend:
            service:
              name: wordpress
              port:
                number: 80
