apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: "/mnt/mysql-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - controlplane