apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 500Mi
  storageClassName: mysql-storage
 